### ISSUE TITLE
Security Issue 

### ISSUE THREAD

**Issue by liampauling** [deworben/betfairTennisAnalysis#2]
Nice username, password and appKey...

**Comment by deworben** [comment]
I cannot thank you enough for this! I'm just learning git and am such a noob. Thank you so much

**Comment by deworben** [comment]
You are a god send @liampauling, karma will be on your side forever. THANK YOU!

**Comment by liampauling** [comment]
No problem, you need to carry out a purge and change password / appKey with betfair.

https://help.github.com/articles/removing-sensitive-data-from-a-repository/

https://github.com/deworben/betfairTennisAnalysis/blob/de9cd9050ca2a55f24afd6607c4b539ddef3d53f/christmasTesting/everythingTogether.py

**Comment by deworben** [comment]
You are the best @liampauling. I'll do that right away. If you ever need anything done that I can help with, please let me know.
